<a href="https://colab.research.google.com/github/AhmedGamalSobhi/Github-example/blob/master/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
# scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [3]:
# vector
vector = torch.tensor((7, 7))
vector

tensor([7, 7])

In [4]:
# MATRIX
MATRIX = torch.tensor(((7, 8),(9, 10)))
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [6]:
# TENSOR
TENSOR = torch.tensor(((1, 2, 3),
                         (3, 6, 9),
                         (2, 4, 5)))
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])